package com.example.brainxp.core.ui

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

internal val BrainXPLightColors =
    lightColorScheme(
        primary = Tokens.Blue600,
        onPrimary = Tokens.Neutral0,
        primaryContainer = Tokens.Blue50,
        onPrimaryContainer = Tokens.Blue700,
        inversePrimary = Tokens.Blue300,
        secondary = Tokens.Blue700,
        onSecondary = Tokens.Neutral0,
        secondaryContainer = Tokens.Blue100,
        onSecondaryContainer = Tokens.Blue800,
        tertiary = Tokens.Neutral700,
        onTertiary = Tokens.Neutral0,
        tertiaryContainer = Tokens.Neutral100,
        onTertiaryContainer = Tokens.Neutral800,
        background = Tokens.Page,
        onBackground = Tokens.Neutral900,
        surface = Tokens.Neutral0,
        onSurface = Tokens.Neutral900,
        surfaceVariant = Tokens.Neutral100,
        onSurfaceVariant = Tokens.Neutral500,
        surfaceContainer = Tokens.Neutral0,
        surfaceContainerHigh = Tokens.Neutral100,
        surfaceContainerHighest = Tokens.Neutral200,
        inverseSurface = Tokens.Neutral900,
        inverseOnSurface = Tokens.Neutral0,
        outline = Tokens.Neutral200,
        outlineVariant = Tokens.Neutral300,
        error = Tokens.Alert,
        onError = Tokens.Neutral0,
        errorContainer = Tokens.AlertSurface,
        onErrorContainer = Tokens.AlertInk,
        scrim = Tokens.Neutral900,
    )

internal val BrainXPDarkColors =
    darkColorScheme(
        primary = Tokens.Blue300,
        onPrimary = Tokens.Blue900,
        primaryContainer = Tokens.Blue800,
        onPrimaryContainer = Tokens.Blue100,
        inversePrimary = Tokens.Blue600,
        secondary = Tokens.Blue100,
        onSecondary = Tokens.Blue900,
        secondaryContainer = Tokens.Blue800,
        onSecondaryContainer = Tokens.Blue100,
        tertiary = Tokens.Neutral300,
        onTertiary = Tokens.Blue900,
        tertiaryContainer = Tokens.Blue800,
        onTertiaryContainer = Tokens.Neutral100,
        background = Tokens.Blue900,
        onBackground = Tokens.Neutral0,
        surface = Tokens.Blue900,
        onSurface = Tokens.Neutral0,
        surfaceVariant = Tokens.Blue800,
        onSurfaceVariant = Tokens.Blue300,
        surfaceContainer = Tokens.Blue800,
        surfaceContainerHigh = Tokens.Blue700,
        surfaceContainerHighest = Tokens.Blue700,
        inverseSurface = Tokens.Neutral0,
        inverseOnSurface = Tokens.Neutral900,
        outline = Tokens.Blue700,
        outlineVariant = Tokens.Blue800,
        error = Tokens.Alert,
        onError = Tokens.Neutral0,
        errorContainer = Tokens.AlertInk,
        onErrorContainer = Tokens.AlertSurface,
        scrim = Tokens.Blue900,
    )
