naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

complexity:
  LongParameterList:
    ignoreAnnotated: ['Composable']
  LongMethod:
    ignoreAnnotated: ['Composable']

style:
  MagicNumber:
    ignorePropertyDeclaration: true
  MaxLineLength:
    maxLineLength: 140
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
  ReturnCount:
    excludeGuardClauses: true
