naming:
  FunctionNaming:
    ignoreAnnotated: ['Composable']

style:
  MagicNumber:
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
  ReturnCount:
    excludeGuardClauses: true
